- role: Associate Editor
  venue: IEEE Robotics and Automation Letters (RA-L)

- role: Reviewer
  venue: IEEE Transactions on Robotics (T-RO), The International Journal of Robotics Research (IJRR), and other robotics journals and conferences
